[package]
name = "yact"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.30.0"
crossterm = "0.28"
anyhow = "1.0.101"
reqwest = { version = "0.13.2", features = ["json"] }
urlencoding = "2.1"
serde = "1.0.228"
serde_json = "1.0.149"
tokio = { version = "1.0", features = ["full"] }
